# Generated by Django 4.0.5 on 2022-07-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
